### ISSUE TITLE
When a user is querying, all dropdown menus will only display correct values

### ISSUE THREAD

**Issue by sawyerball** [cs481-ekh/s23-wildfire-wizards#17]
- [ ] The state dropdown menu is correct #25
- [ ] The county dropdown menu is correct for every state #26
- [ ] The year dropdown menu is correct  #27
- [x] #36
