### ISSUE TITLE
Deploy a working container to the SDP servers

### ISSUE THREAD

**Issue by sawyerball** [cs481-ekh/s23-wildfire-wizards#53]
As a developer, I want to deploy the project to the SDP servers so that I can access the project without running it locally.

## Definition of Done
- [x] Accessible through the Boise State SDP site (sdp.boisestate.edu)
- [ ] Make sure site has proper data 

## Tasks
- [x] Make sure project is ready for deployment; follow instructions at https://sdp.boisestate.edu/cs481/info in deployment section
- [x] #54
