### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by ethanraygorbsu** [cs481-ekh/s23-wildfire-wizards#9]
- [ ] When a fire instance is clicked on the data shown is not essential, it show name, size, and cause first #11 
- [ ] When showing “Additional Details”, we need to only show a fraction of the variables. These variables should be determined when a user is querying and there should be another option to see all variables #12
- [ ] When showing Additional Details, variable descriptions should be available in the websites UI not in an external google sheet #18
- [ ] When showing additional details, true/false values should display as 1/0 #20
- [ ] Stretch goal: The website will be mobile compatible #21
